# SPDX-FileCopyrightText: 2024 Victor Dahmen
# SPDX-License-Identifier: Apache-2.0

package:
  name: unit
  version: "1.32.1-1"
  description: "NGINX Unit"
  epoch: 0
  copyright:
    - license: Apache-2.0
  target-architecture:
    - x86_64
  checks:
    disabled:
      - empty

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - autoconf
      - automake
      - brotli-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - gd-dev
      - geoip-dev
      - libmaxminddb-dev
      - libxml2-dev
      - libxslt-dev
      - luajit-dev
      - openssl-dev
      - pcre-dev
      - perl-dev
      - pkgconf
      - zeromq-dev
      - zlib-dev
      - php-8.3-dev@local
      - php-8.3-embed@local

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/nginx/unit
      tag: "${{package.version}}"
  - name: Configure
    runs: |
      ./configure \
        --prefix="/usr" \
        --localstatedir="/var" \
        --statedir="/var/lib/unit" \
        --control="unix:/run/control.unit.sock" \
        --pid="/var/run/unit.pid" \
        --log="/var/log/unit.log" \
        --tmpdir=/tmp \
        --modulesdir="/usr/local/lib/unit/modules/" \
        --openssl \
        --user=unit \
        --group=unit
  - name: Configure PHP 8.3 module
    runs: ./configure php --module=php83
  - uses: autoconf/make
  - uses: autoconf/make-install
  - uses: strip

subpackages:
  - name: "${{package.name}}-php83"
    pipeline:
      - name: Split out module
        runs: |
          mkdir -p "${{targets.subpkgdir}}/usr/local/lib/unit/modules/"
          mv ${{targets.destdir}}/usr/local/lib/unit/modules/php83.unit.so ${{targets.subpkgdir}}/usr/local/lib/unit/modules/php83.unit.so
  - name: ${{package.name}}-doc
    pipeline:
      - uses: split/manpages
